DROP DATABASE IF EXISTS CampaignManager;
CREATE DATABASE CampaignManager;
USE CampaignManager;

CREATE TABLE USER (
  USER_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  USER_NAME varchar(255) NOT NULL,
  USER_PASSWORD varchar(255) NOT NULL,
  USER_QUESTION1 varchar(255) NOT NULL,
  USER_ANSWER1 varchar(255) NOT NULL,
  USER_QUESTION2 varchar(255) NOT NULL,
  USER_ANSWER2 varchar(255) NOT NULL,
  PRIMARY KEY (USER_ID),
  UNIQUE KEY USER_ID(USER_ID)
);


CREATE TABLE CAMPAIGN (
  CAM_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  CAM_NAME varchar(255) NOT NULL,
  CAM_DESC TEXT,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (CAM_ID),
  UNIQUE KEY CAM_ID(CAM_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ADVENTURE (
  ADV_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  ADV_NAME varchar(255) NOT NULL,
  ADV_DESC TEXT,
  CAM_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (ADV_ID),
  UNIQUE KEY ADV_ID (ADV_ID),
  FOREIGN KEY (CAM_ID) REFERENCES CAMPAIGN(CAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ACT (
  ACT_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  ACT_NAME varchar(255) NOT NULL,
  ACT_STORY TEXT,
  ADV_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (ACT_ID),
  UNIQUE KEY ACT_ID (ACT_ID),
  FOREIGN KEY (ADV_ID) REFERENCES ADVENTURE(ADV_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ENCOUNTER (
  ENC_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  ENC_NAME varchar(255) NOT NULL,
  ENC_DESC varchar(255),
  ACT_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (ENC_ID),
  UNIQUE KEY ENC_ID (ENC_ID),
  FOREIGN KEY (ACT_ID) REFERENCES ACT(ACT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE MONSTER (
  MON_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  MON_NAME varchar(255) NOT NULL,
  MON_SIZETYPEALIGN varchar(255) NOT NULL,
  MON_AC varchar(30) NOT NULL,
  MON_HP varchar(30) NOT NULL,
  MON_SPEED varchar(30) NOT NULL,
  MON_STR varchar(30) NOT NULL,
  MON_DEX varchar(30) NOT NULL,
  MON_CON varchar(30) NOT NULL,
  MON_INT varchar(30) NOT NULL,
  MON_WIS varchar(30) NOT NULL,
  MON_CHA varchar(30) NOT NULL,
  MON_VULNERABILITIES varchar(255),
  MON_RESISTANCES varchar(255),
  MON_IMMUNITIES varchar(255),
  MON_LANGUAGES varchar(255),
  MON_CR varchar(30) NOT NULL,
  MON_SKILLS varchar(255),
  MON_PROFBONUS varchar(30),
  MON_SAVETHROWS varchar(255),
  MON_SENSES varchar(255) NOT NULL,
  MON_ABILITIES TEXT,
  MON_ACTIONS TEXT NOT NULL,
  MON_LEGENDARYACTIONS TEXT,
  
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (MON_ID),
  UNIQUE KEY MON_ID (MON_ID),
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ENCMON(
  ENCMON_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  MON_ID bigint(20) unsigned NOT NULL,
  ENC_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY(ENCMON_ID),
  UNIQUE KEY ENCMON_ID (ENCMON_ID),
  FOREIGN KEY (MON_ID) REFERENCES MONSTER(MON_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (ENC_ID) REFERENCES ENCOUNTER(ENC_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE NPC (
  NPC_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  NPC_NAME varchar(255) NOT NULL,
  NPC_LEVEL varchar(20) NOT NULL,
  NPC_RACE varchar(255) NOT NULL,
  NPC_CLASS varchar(255) NOT NULL,
  NPC_ALIGN varchar(255) NOT NULL,
  NPC_AC varchar(30) NOT NULL,
  NPC_HP varchar(30) NOT NULL,
  NPC_SPEED varchar(30) NOT NULL,
  NPC_STR varchar(30) NOT NULL,
  NPC_DEX varchar(30) NOT NULL,
  NPC_CON varchar(30) NOT NULL,
  NPC_INT varchar(30) NOT NULL,
  NPC_WIS varchar(30) NOT NULL,
  NPC_CHA varchar(30) NOT NULL,
  NPC_LANGUAGES varchar(255),
  NPC_CR varchar(30) NOT NULL,
  NPC_SKILLS varchar(255) NOT NULL,
  NPC_PROFBONUS varchar(30) NOT NULL,
  NPC_SAVETHROWS varchar(255),
  NPC_ABILITIES TEXT NOT NULL,
  NPC_ACTIONS TEXT NOT NULL,
  NPC_BIO TEXT NOT NULL,
  
  CAM_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (NPC_ID),
  UNIQUE KEY NPC_ID (NPC_ID),
  FOREIGN KEY (CAM_ID) REFERENCES CAMPAIGN(CAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ACTNPC(
  ACTNPC_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  ACT_ID bigint(20) unsigned NOT NULL,
  NPC_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY(ACTNPC_ID),
  UNIQUE KEY ACTNPC_ID (ACTNPC_ID),
  FOREIGN KEY (ACT_ID) REFERENCES ACT(ACT_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (NPC_ID) REFERENCES NPC(NPC_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE PC (
  PC_ID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PC_NAME varchar(255) NOT NULL,
  PC_LEVEL varchar(20) NOT NULL,
  PC_RACE varchar(255) NOT NULL,
  PC_CLASS varchar(255) NOT NULL,
  PC_ALIGN varchar(255) NOT NULL,
  PC_AC varchar(30) NOT NULL,
  PC_HP varchar(30) NOT NULL,
  PC_SPEED varchar(30) NOT NULL,
  PC_STR varchar(30) NOT NULL,
  PC_DEX varchar(30) NOT NULL,
  PC_CON varchar(30) NOT NULL,
  PC_INT varchar(30) NOT NULL,
  PC_WIS varchar(30) NOT NULL,
  PC_CHA varchar(30) NOT NULL,
  PC_LANGUAGES varchar(255),
  PC_SKILLS varchar(255),
  PC_PROFBONUS varchar(30),
  PC_SAVETHROWS varchar(255),
  PC_ABILITIES TEXT,
  PC_ACTIONS TEXT,
  PC_BIO TEXT NOT NULL,
  
  CAM_ID bigint(20) unsigned NOT NULL,
  USER_ID bigint(20) unsigned NOT NULL,
  
  PRIMARY KEY (PC_ID),
  UNIQUE KEY PC_ID (PC_ID),
  FOREIGN KEY (CAM_ID) REFERENCES CAMPAIGN(CAM_ID) ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE
);